version: "3.8"

services:
  backend:
    image: ghcr.io/sagiamda-l/tax-parser/backend:latest
    container_name: tax-backend
    volumes:
      - tax_db_data:/app/data
    environment:
      - SPREADSHEET_ID=your_google_sheet_id_here # 여기에 시트 ID 입력
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: ghcr.io/sagiamda-l/tax-parser/frontend:latest
    container_name: tax-frontend
    ports:
      - "3000:80"
    restart: always

volumes:
  tax_db_data:
